package amart.gui;

import amart.dao.OrderDAO;
import amart.dao.ProductsDAO;
import amart.pojo.ProductsPojo;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class BillingFrame extends javax.swing.JFrame {

    ArrayList<ProductsPojo> al=new ArrayList<>();
    DefaultTableModel tm; 
    double grTotal=0.0;
    public BillingFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        tm=(DefaultTableModel)jtProducts.getModel();
        txtPId.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnGenBill = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProducts = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jlTotal = new javax.swing.JLabel();
        txtPId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Product Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 140, 30));

        btnGenBill.setBackground(new java.awt.Color(255, 204, 153));
        btnGenBill.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnGenBill.setForeground(new java.awt.Color(0, 0, 0));
        btnGenBill.setText("Generate Bill");
        btnGenBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenBillActionPerformed(evt);
            }
        });
        jPanel1.add(btnGenBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 650, 170, 40));

        btnLogout.setBackground(new java.awt.Color(204, 204, 255));
        btnLogout.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 109, 40));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 153));
        jLabel1.setText("Billing Option");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 440, 39));

        jtProducts.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jtProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PRODUCT ID", "PRODUCT NAME", "PRODUCT COMPANY", "PRODUCT PRICE", "OUR PRICE", "QUANTITY", "TAX", "TOTAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtProducts.setRowHeight(30);
        jScrollPane1.setViewportView(jtProducts);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 1000, 470));

        btnBack.setBackground(new java.awt.Color(204, 204, 255));
        btnBack.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 0, 0));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, 109, 40));

        jlTotal.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jlTotal.setForeground(new java.awt.Color(0, 0, 0));
        jlTotal.setText("Product Id");
        jPanel1.add(jlTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 660, 160, -1));

        txtPId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtPId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtPId, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 180, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amart/images/stocks1.jpg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 800));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenBillActionPerformed
       try
       {
         String ordId=OrderDAO.getNextOrderId();

        PaymentFrame pf = new PaymentFrame(ordId, grTotal, al);
                    pf.setVisible(true);
                    this.dispose();
            
       }catch(SQLException e1)
        {
        JOptionPane.showMessageDialog(this,"DataBase Error ! ","Error ",JOptionPane.ERROR_MESSAGE);  
        e1.printStackTrace();
        }
         
       
    }//GEN-LAST:event_btnGenBillActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new ReceptionistOptionsFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtPIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPIdActionPerformed
       if(txtPId.getText().trim().isEmpty())
       {
       JOptionPane.showMessageDialog(this,"Please Enter Product Id !! ","ERROR",JOptionPane.ERROR_MESSAGE);  
        return;
       } 
       loadItemList(txtPId.getText().trim());
    }//GEN-LAST:event_txtPIdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BillingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BillingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BillingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BillingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BillingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGenBill;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlTotal;
    private javax.swing.JTable jtProducts;
    private javax.swing.JTextField txtPId;
    // End of variables declaration//GEN-END:variables

    private void loadItemList(String pid) {
        try{
        ProductsPojo p=ProductsDAO.getProductDetails(pid);
        if(p.getProductId()==null)
        {
        JOptionPane.showMessageDialog(this,"Please Enter A Valid Product Id !! ","ERROR",JOptionPane.ERROR_MESSAGE);  
        return;
        }
        int index=getProductId(pid);
        if(index==-1)
        {
          Object [] rows=new Object[8];
          int quan=1;
          double amt=quan*p.getOurPrice();
          p.setQuantity(quan);
          p.setTotal(amt+(amt*p.getTax()/100));
          rows[0]=p.getProductId();
          rows[1]=p.getProductName();
          rows[2]=p.getProductCompany();
          rows[3]=p.getProductPrice();
          rows[4]=p.getOurPrice();
          rows[5]=p.getQuantity();
          rows[6]=p.getTax();
          rows[7]=p.getTotal();
          tm.addRow(rows);
          al.add(p);
          grTotal+=p.getTotal();
        }
        else
        {
          ProductsPojo prd=al.get(index);
          int oldq=(int)tm.getValueAt(index,5);
          double amt=prd.getOurPrice();
          int tax=prd.getTax();
          amt=amt+(amt*tax/100);
          double total=(double)tm.getValueAt(index,7);
          tm.setValueAt(++oldq,index,5);
          tm.setValueAt(total+amt,index,7);
          grTotal+=amt;
          prd.setQuantity(oldq);
          prd.setTotal(total+amt);
          al.set(index,prd);
        } 
        }catch(SQLException e1)
        {
        JOptionPane.showMessageDialog(this,"DataBase Error ! ","Error ",JOptionPane.ERROR_MESSAGE);  
        e1.printStackTrace();
        }
       catch(NumberFormatException e1)
       {
       JOptionPane.showMessageDialog(this,"Please fill numeric value for salary ","Error ",JOptionPane.ERROR_MESSAGE);  
       e1.printStackTrace();
       }   
    }
    
   private int getProductId(String pid)
   {
   int index=-1;
   for(int i=0;i<al.size();i++)
     {
       ProductsPojo p=al.get(i);
       if(p.getProductId().equals(pid))
        {
         index=i;
         break;
      }  
   
     }
   return index;
   
   }
}
