
package amart.gui;

import amart.dao.OrderDAO;
import amart.dao.PaymentDAO;
import amart.dao.ProductsDAO;
import amart.pojo.PaymentPojo;
import amart.pojo.ProductsPojo;
import java.util.ArrayList;
import javax.swing.JOptionPane;



public class PaymentFrame extends javax.swing.JFrame {

  private String orderId;
  private double amount;
  private ArrayList<ProductsPojo> al;
    
    public PaymentFrame() {
        initComponents();
      this.setLocationRelativeTo(this);
        
        txtAmount.setEditable(false);
        txtTId.setEditable(false);
    }
    
    public PaymentFrame(String orderId,double amount,
                   ArrayList<ProductsPojo> al) {
    initComponents();

    this.orderId = orderId;
    this.amount = amount;
    this.al = al;

    txtOrderId.setText(orderId);
    txtAmount.setText(String.valueOf(amount));

    txtOrderId.setEditable(false);
    txtAmount.setEditable(false);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTId = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cbPayment = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnPay = new javax.swing.JButton();
        btnLogout1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Order Id");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 140, 30));

        txtOrderId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtOrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOrderIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtOrderId, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 200, 180, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Total Amount");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 180, 30));

        txtAmount.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });
        jPanel1.add(txtAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, 180, 30));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Transaction ID");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 330, 180, 30));

        txtTId.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtTId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtTId, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 180, 30));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Payment Options");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, 330, 50));

        cbPayment.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cbPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "UPI", "Card", "Net Banking" }));
        cbPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPaymentActionPerformed(evt);
            }
        });
        jPanel1.add(cbPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 200, 40));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Payment Mode");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 180, 30));

        btnPay.setBackground(new java.awt.Color(204, 204, 255));
        btnPay.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPay.setForeground(new java.awt.Color(0, 0, 0));
        btnPay.setText("Pay");
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });
        jPanel1.add(btnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 130, 40));

        btnLogout1.setBackground(new java.awt.Color(204, 204, 255));
        btnLogout1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogout1.setForeground(new java.awt.Color(0, 0, 0));
        btnLogout1.setText("Logout");
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 10, 109, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/amart/images/Receptions.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOrderIdActionPerformed
        
    }//GEN-LAST:event_txtOrderIdActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
       
    }//GEN-LAST:event_txtAmountActionPerformed

    private void txtTIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTIdActionPerformed
        
    }//GEN-LAST:event_txtTIdActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        try {

    String mode = cbPayment.getSelectedItem().toString();
String txnId = txtTId.getText().trim();

if(txnId.isEmpty()) {
    if(mode.equals("Cash"))
        txnId = "CASH" + System.currentTimeMillis();
    else if(mode.equals("UPI"))
        txnId = "UPI" + System.currentTimeMillis();
    else if(mode.equals("Card"))
        txnId = "CARD" + System.currentTimeMillis();
    else
        txnId = "NET" + System.currentTimeMillis();

    txtTId.setText(txnId);
}

    PaymentPojo p = new PaymentPojo();

    p.setOrderId(orderId);
    p.setAmount(amount);
    p.setPaymentMode(mode);
    p.setTransactionId(txnId);
    p.setPaymentStatus("SUCCESS");

    boolean paymentDone = PaymentDAO.savePayment(p);

    if(paymentDone)
    {
        if(OrderDAO.addOrder(al, orderId)
                && ProductsDAO.updateStocks(al))
        {
            JOptionPane.showMessageDialog(this,
                    "Payment Successful");
            new ReciptFrame().setVisible(true);
            this.dispose();

//            new BillingFrame().setVisible(true);
//            this.dispose();
        }
    }
    else
    {
        JOptionPane.showMessageDialog(this,
                "Payment Failed");
    }

}
catch(Exception e)
{
    e.printStackTrace();
    JOptionPane.showMessageDialog(this,
            "Error : "+e.getMessage());
}
    }//GEN-LAST:event_btnPayActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        new LoginFrame().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void cbPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPaymentActionPerformed
        
    String mode = cbPayment.getSelectedItem().toString();

    if(mode.equals("Cash")){
        txtTId.setEnabled(false);
        txtTId.setText("");
    }
    else{
        txtTId.setEnabled(true);
    }
    }//GEN-LAST:event_cbPaymentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout1;
    private javax.swing.JButton btnPay;
    private javax.swing.JComboBox<String> cbPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtTId;
    // End of variables declaration//GEN-END:variables
}
